version: '2'

services:
    # PostgreSQL database
    db:
        image: postgres:9.6
        hostname: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5432:5432"

    # Django web server
    web:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: ./run_web--dev.sh
        volumes:
            - .:/srv/www/metameme/metameme  # mount current directory inside container
        ports:
            - "8010:8010"
        # set up links so that web knows about db, rabbit and redis
        links:
            - db
        depends_on:
            - db
